### ISSUE TITLE
BSD or MIT

### ISSUE THREAD

**Issue by ignatenkobrain** [dropbox/rust-brotli#41]
Hello, Cargo.toml lists BSD OR MIT, however LICENSE file contains only info about BSD... Who is right?

**Comment by danielrh** [comment]
I suppose the license file is right... I can adjust the Cargo.toml
both licenses are sufficiently permissive that they are quite compatible.

**Comment by decathorpe** [comment]
Looks like this issue is still unresolved as of today?

**Comment by nyurik** [comment]
Most Rust projects prefer to use `Apache OR MIT` approach because MIT is not very compatible with GPL (if my memory is serving me right), and so having two clause approach allows users to use code everywhere more freely.

**Comment by decathorpe** [comment]
Then the license text for MIT should probably be added to this repo too?

The current license file (https://github.com/dropbox/rust-brotli/blob/master/LICENSE) file only contains the BSD-3-Clause license text, but the MIT license requires that license text is included with redistributed sources.

Usually dual-licensed crates handle this by having two separate license files (i.e. LICENSE-Apache and LICENSE-MIT, in most cases).

> MIT is not very compatible with GPL

As far as I know, the problem wrt/ GPL compatibility is actually caused by the Apache-2.0 license, not the MIT license.

**Comment by danielrh** [comment]
Hmmm should probably copy the license from https://github.com/google/brotli/blob/master/LICENSE

**Comment by musicinmybrain** [comment]
It would be great to see something happen here. Since the [`MIT` license](https://spdx.org/licenses/MIT.html) requires including the copyright and permission notices (the license text) in copies or substantial portions, it’s not possible for people to actually use this software under `MIT` terms if there’s no original license text available. This makes the crate effectively `BSD-3-Clause`-only for those who care about license compliance, and it creates a pitfall and an annoyance for people like distribution packagers, who have to patch the license metadata in `Cargo.toml` to avoid misleading people.

**Comment by musicinmybrain** [comment]
As a further wrinkle, similarly to https://github.com/dropbox/rust-brotli-decompressor/issues/9#issuecomment-1145129711, it turns out that one file is owned by Google and distributed only under `MIT` terms, so the crate isn’t even properly `BSD-3-Clause`; it would have to be `BSD-3-Clause AND MIT`, and the license text for that file needs to be present.

https://github.com/dropbox/rust-brotli/blob/37d403b437c3cbd1c686871a4167290aab401704/src/enc/entropy_encode.rs#L1-L5

Please do something about this!

**Comment by musicinmybrain** [comment]
It looks like `entropy_encode.rs` is based on https://github.com/google/brotli/blob/v1.1.0/c/enc/entropy_encode.c, so (despite the discrepancy in copyright statement between the header and the license file), https://github.com/google/brotli/blob/v1.1.0/LICENSE is probably the appropriate license text here.
