### ISSUE TITLE
Is this library for decompression only and doesn't enclude the compression?

### ISSUE THREAD

**Issue by khaledkbadr** [dropbox/rust-brotli#5]

**Comment by danielrh** [comment]
One day it would be nice to have compression--but it is significantly more code with significantly more heuristics. Also the main brotli library changes quite often, so this would be playing catchup at all points.
If someone wanted to contribute that functionality I'm all for merging it in and giving that author commit access here.

**Comment by danielrh** [comment]
Working on this issue in a branch
https://github.com/dropbox/rust-brotli/tree/encoder_wip
still a lot of code to go...but it's on its way

**Comment by danielrh** [comment]
It seems to be working--I've only tested a few files so far and a few compression settings.
If you want to try it out, let me know if you run into any issues...
the src/enc/test.rs shows examples about how to set it up--though I recommend using the default memory allocator rather than the wild no-std ones I used in there...I'll make more samples later in the week

**Comment by khaledkbadr** [comment]
Thanks, man. I will try it out and report issues if I find any

**Comment by danielrh** [comment]
I just pushed a branch that sets it up as a command line tool (pass the -c flag for compression... -9 for quality 9, etc...)
you can use it as a lib too--I've only implemented the reader interface thus far
